/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parkingslot;

import com.sun.corba.se.impl.interceptors.SlotTable;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Win10
 */
public class MenuFrame extends javax.swing.JFrame {
    /** Creates new form MenuFrame */
    public static Object slots[][];
    public MenuFrame() {        
        initComponents();
        ImageIcon icon = new ImageIcon("src/parkingslot/misc/icon.png");
        this.setIconImage(icon.getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        slotTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JButton();
        addvehicle = new javax.swing.JButton();
        retrieve = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        park = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Parking Slot System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //slotTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        slotTable.getTableHeader().setReorderingAllowed(false);
        ParkingSlot ps = new ParkingSlot();
        Statement st = ps.connectDB();
        slots = new Object[50][6];
        String count_query = "SELECT * FROM Slot";
        int x = 0;
        int numbers[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50};
        int slot_get[];
        slot_get = new int[slots.length + 1];
        try {
            ResultSet rsc = st.executeQuery(count_query);
            while(rsc.next() && x < slots.length)
            {
                String id = rsc.getString("ID");
                int slot = rsc.getInt("Slot Number");
                String vehicle = rsc.getString("Vehicle Number");
                String name = rsc.getString("Name");
                String type = rsc.getString("Type");
                String dt = rsc.getString("Date Parked");
                slots[x][0] = slot;
                slots[x][1] = id;
                slots[x][2] = name;
                slots[x][3] = vehicle;
                slots[x][4] = type;
                slots[x][5] = dt;
                //                    slot_get[x] = slot;
                x++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        slotTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        slotTable.setModel(new javax.swing.table.DefaultTableModel(
            slots,
            new String [] {
                "Slots", "ID", "Name", "Vehicle Number", "Typed", "Date Parked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        slotTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        slotTable.setFocusable(false);
        jScrollPane1.setViewportView(slotTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 530, 290));

        jPanel1.setBackground(new java.awt.Color(11, 11, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setBackground(new java.awt.Color(192, 87, 194));
        register.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Register a person");
        register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        register.setRequestFocusEnabled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, 33));

        addvehicle.setBackground(new java.awt.Color(192, 87, 194));
        addvehicle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addvehicle.setForeground(new java.awt.Color(255, 255, 255));
        addvehicle.setText("Add a vehicle");
        addvehicle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        addvehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvehicleActionPerformed(evt);
            }
        });
        jPanel1.add(addvehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 33));

        retrieve.setBackground(new java.awt.Color(192, 87, 194));
        retrieve.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        retrieve.setForeground(new java.awt.Color(255, 255, 255));
        retrieve.setText("Retrieve a vehicle");
        retrieve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveActionPerformed(evt);
            }
        });
        jPanel1.add(retrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, 33));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Exit");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 180, 33));

        park.setBackground(new java.awt.Color(192, 87, 194));
        park.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        park.setForeground(new java.awt.Color(255, 255, 255));
        park.setText("Park a vehicle");
        park.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        park.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkActionPerformed(evt);
            }
        });
        jPanel1.add(park, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 33));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        new Registration().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    private void addvehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvehicleActionPerformed
        // TODO add your handling code here:
        new AddVehicle().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addvehicleActionPerformed

    private void retrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveActionPerformed
        // TODO add your handling code here:
        new Retrieve().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retrieveActionPerformed

    private void parkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkActionPerformed
        // TODO add your handling code here:
        new Park().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_parkActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(rootPane, "Do you want to exit?", "Exit", JOptionPane.OK_CANCEL_OPTION);
        if(res == JOptionPane.OK_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes","No"};
        int PromptResult = JOptionPane.showOptionDialog(null, 
            "Are you sure you want to exit?", "Exit", 
            JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, 
            ObjButtons,ObjButtons[1]);
        if(PromptResult==0)
        {
          System.exit(0);          
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>                      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvehicle;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton park;
    private javax.swing.JButton register;
    private javax.swing.JButton retrieve;
    private javax.swing.JTable slotTable;
    // End of variables declaration//GEN-END:variables

}
